/* ============================================================
   SORU BANKASI — tüm PDF kaynaklarından derlenen sorular + çözümler
   Math LaTeX: \( \) inline, \[ \] display (MathJax config'inde tanımlı)
   Alanlar: topic, q, opts?(şıklar), correct?(0-tabanlı), a(cevap), fig?(şekil)
   ============================================================ */
const QBANK = [

/* ---------- FOURIER DÖNÜŞÜMÜ ---------- */
{"topic":"fourier","q":"\\( f(t)=\\begin{cases}3 & -2\\le t\\le 2\\\\ 0 & \\text{diğer}\\end{cases} \\). Fourier dönüşümü?","opts":["\\( \\frac{6}{\\omega}\\sin 2\\omega \\)","\\( -\\frac{6}{\\omega}\\sin 2\\omega \\)","\\( \\frac{6}{\\omega}\\sin 4\\omega \\)","\\( \\frac{6}{\\omega}\\cos 2\\omega \\)"],"correct":0,"a":"Genişlik 4, yükseklik 3 dikdörtgen: \\( \\int_{-2}^{2}3e^{-j\\omega t}dt=\\frac{6}{\\omega}\\sin 2\\omega \\).","fig":""},
{"topic":"fourier","q":"\\( x(t)=e^{-at^2},\\ a>0 \\) (Gauss). \\( X(j\\omega)=? \\)","opts":["\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4a} \\)","\\( -\\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4a} \\)","\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^4/4a} \\)","\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4} \\)"],"correct":0,"a":"Gauss'un dönüşümü yine Gauss.","fig":""},
{"topic":"fourier","q":"\\( x(t)=\\begin{cases}1 & -a\\le t\\le a\\\\ 0 & \\text{diğer}\\end{cases} \\). \\( X(j\\omega)=? \\)","opts":["\\( 2a\\,\\mathrm{sinc}(\\omega a) \\)","\\( 2a\\,\\mathrm{sinc}(\\omega) \\)","\\( 2\\,\\mathrm{sinc}(\\omega a) \\)","\\( 4a\\,\\mathrm{sinc}(\\omega a) \\)"],"correct":0,"a":"Genişlik \\(2a\\) dikdörtgen \\(\\to 2a\\,\\mathrm{sinc}(\\omega a)\\).","fig":""},
{"topic":"fourier","q":"\\( x(t)=\\begin{cases}e^{-at} & t\\ge 0\\\\ e^{at} & t<0\\end{cases} \\) (çift üstel). \\( X(j\\omega)=? \\)","opts":["\\( \\frac{1}{\\sqrt{2\\pi}}\\frac{2a}{a^2+\\omega^2} \\)","\\( \\frac{1}{\\sqrt{2}}\\frac{2a}{a^2+\\omega^2} \\)","\\( \\frac{1}{\\pi}\\frac{2a}{a^2+\\omega^2} \\)","\\( \\frac{1}{\\sqrt{2\\pi}}\\frac{2a}{a^2-\\omega^2} \\)"],"correct":0,"a":"\\( \\frac{1}{\\sqrt{2\\pi}}\\left[\\frac{1}{a-j\\omega}+\\frac{1}{a+j\\omega}\\right]=\\frac{1}{\\sqrt{2\\pi}}\\frac{2a}{a^2+\\omega^2} \\).","fig":""},
{"topic":"fourier","q":"Üç birim impuls: \\(t=-4,0,+4\\)'te yükseklik 1. \\( X(j\\omega)=? \\)","opts":["\\( 1+2\\cos(4\\omega) \\)","\\( 1-2\\cos(4\\omega) \\)","\\( 1+2\\cos(2\\omega) \\)","\\( 1+2\\sin(4\\omega) \\)"],"correct":0,"a":"\\( e^{j4\\omega}+1+e^{-j4\\omega}=1+2\\cos(4\\omega) \\).","fig":"x(t): t=-4, 0, +4 noktalarında yükseklik 1 olan birim impulslar."},
{"topic":"fourier","q":"\\( x(t)=e^{-2t+4}\\,u(t-2) \\). \\( X(j\\omega)=? \\)","opts":["\\( \\frac{e^{-2j\\omega}}{j\\omega+2} \\)","\\( \\frac{e^{-2j\\omega}}{j\\omega-2} \\)","\\( \\frac{e^{-j\\omega}}{j\\omega+2} \\)","\\( \\frac{e^{-2j\\omega}}{\\omega+2} \\)"],"correct":0,"a":"\\( x(t)=e^{-2(t-2)}u(t-2) \\); zaman kayması \\(\\to \\frac{e^{-2j\\omega}}{j\\omega+2}\\).","fig":""},
{"topic":"fourier","q":"\\( x(t)=e^{-at}u(t),\\ a>0 \\). Sürekli Fourier dönüşümü?","opts":["\\( \\frac{1}{a+j\\omega} \\)","\\( \\frac{1}{a-j\\omega} \\)","\\( \\frac{1}{2a+j\\omega} \\)","\\( \\frac{1}{a^2+j\\omega^2} \\)"],"correct":0,"a":"Temel çift.","fig":""},
{"topic":"fourier","q":"Ters Fourier: \\( X(j\\omega)=1 \\) (yalnız \\(|\\omega|\\in[\\pi,2\\pi]\\)'de, çift). \\( x(t)=? \\)","a":"\\( x(t)=\\frac{1}{2\\pi}\\Big(\\int_{-2\\pi}^{-\\pi}+\\int_{\\pi}^{2\\pi}\\Big)e^{j\\omega t}d\\omega = 2\\,\\mathrm{sinc}(2t)-\\mathrm{sinc}(t) \\).","fig":"X(jw): [-2π,-π] ve [π,2π] aralıklarında yükseklik 1, dışında 0."},
{"topic":"fourier","q":"Frekans yanıtı yöntemiyle: \\( y(t)=\\int_{-\\infty}^{\\infty}e^{-\\tau}u(\\tau)\\,3\\cos(t-\\tau-\\pi)\\,d\\tau \\).","opts":["\\( \\frac{\\sqrt3}{2}\\cos(t-\\pi-\\frac{\\pi}{4}) \\)","\\( \\frac{\\sqrt3}{2}\\cos(t+\\pi-\\frac{\\pi}{4}) \\)","\\( \\frac{2}{\\sqrt3}\\cos(t-\\pi-\\frac{\\pi}{4}) \\)","\\( \\frac{\\sqrt3}{4}\\cos(t-\\pi-\\frac{\\pi}{4}) \\)"],"correct":0,"a":"\\( h(t)=e^{-t}u(t),\\ H(j1)=\\frac{1}{1+j}=\\frac{1}{\\sqrt2}\\angle{-\\frac{\\pi}{4}} \\). Genlik \\(\\times\\frac{1}{\\sqrt2}\\), faz \\(-\\frac{\\pi}{4}\\) (cevap anahtarına göre).","fig":""},
{"topic":"fourier","q":"Frekans yanıtı yöntemiyle: \\( y(t)=\\int_{-\\infty}^{\\infty}e^{\\tau}u(-\\tau)\\,2\\cos(t-\\tau+\\pi)\\,d\\tau \\).","a":"\\( h(t)=e^{t}u(-t),\\ H(j\\omega)=\\frac{1}{1-j\\omega} \\). \\( H(j1)=\\frac{1}{\\sqrt2}\\angle{\\frac{\\pi}{4}} \\). Sonuç: \\( y(t)=\\sqrt2\\cos\\!\\left(t-\\frac{3\\pi}{4}\\right) \\).","fig":""},

/* ---------- FOURIER SERİSİ ---------- */
{"topic":"fseries","q":"\\( x(t) \\) periyodu \\(T=3\\): \\( 3\\ (0\\le t<1.5),\\ -3\\ (1.5\\le t<3) \\). Fourier seri katsayısı \\(a_k=?\\)","opts":["\\( \\frac{6}{k\\pi}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( -\\frac{6}{k\\pi}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( \\frac{6}{k}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( \\frac{6}{k\\pi}\\cos(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)"],"correct":0,"a":"\\( a_k=\\frac1T\\int_T x\\,e^{-jk\\omega_0 t}dt \\) ile bulunur.","fig":""},
{"topic":"fseries","q":"\\( x(t)=10\\cos(\\omega_0 t-\\frac{13\\pi}{2})+7\\cos(\\omega_0 t+\\frac{3\\pi}{4})+7\\cos(\\omega_0 t+\\frac{5\\pi}{4}) \\) ifadesini \\(A\\cos(\\omega_0 t+\\phi)\\) formuna getir.","a":"Fazörler: \\( 10e^{-j13\\pi/2}+7e^{j3\\pi/4}+7e^{j5\\pi/4}=-j10-7\\sqrt2\\approx 14.07\\,e^{-j0.948\\pi} \\). \\( x(t)=14.07\\cos(\\omega_0 t-0.948\\pi) \\).","fig":""},
{"topic":"fseries","q":"\\( x(t)=\\sum_{k=-2}^{2}\\frac{1}{1+jk}e^{jkt} \\) sinyalini sinüzoidal biçimde ifade et.","a":"\\( c_0=1,\\ c_{\\pm1}=\\frac{1}{\\sqrt2}e^{\\mp j\\pi/4},\\ c_{\\pm2}=\\frac{1}{\\sqrt5}e^{\\mp j\\arctan 2} \\). \\( x(t)=1+\\frac{2}{\\sqrt2}\\cos(t-\\frac{\\pi}{4})+\\frac{2}{\\sqrt5}\\cos(2t-0.35\\pi) \\).","fig":""},
{"topic":"fseries","q":"\\( x(t)=\\sum_{k=-3}^{3}\\frac{1}{1-jk}e^{-jkt} \\) sinyalini sinüzoidal biçimde ifade et.","a":"\\( |c_0|=1,|c_{\\pm1}|=\\frac{1}{\\sqrt2},|c_{\\pm2}|=\\frac{1}{\\sqrt5},|c_{\\pm3}|=\\frac{1}{\\sqrt{10}} \\), faz \\(\\arctan k\\). \\( x(t)=1+\\frac{2}{\\sqrt2}\\cos(t-\\frac{\\pi}{4})+\\frac{2}{\\sqrt5}\\cos(2t-0.35\\pi)+\\frac{2}{\\sqrt{10}}\\cos(3t-0.40\\pi) \\).","fig":""},

/* ---------- DTFT / FREKANS YANITI ---------- */
{"topic":"dtft","q":"\\( x[n]=\\delta[n+2]-\\delta[n-2] \\). \\( X(e^{j\\omega})=? \\)","opts":["\\( 2j\\sin(2\\omega) \\)","\\( 2j\\cos(2\\omega) \\)","\\( 2j\\sin(4\\omega) \\)","\\( 2\\sin(2\\omega) \\)"],"correct":0,"a":"\\( e^{j2\\omega}-e^{-j2\\omega}=2j\\sin(2\\omega) \\).","fig":""},
{"topic":"dtft","q":"LZD sistem: \\( ay[n-1]+y[n]=x[n] \\). \\( H(e^{j\\omega})=? \\)","opts":["\\( \\frac{1}{1+ae^{-j\\omega}} \\)","\\( \\frac{1}{1-ae^{-j\\omega}} \\)","\\( \\frac{1}{2+ae^{-j\\omega}} \\)","\\( \\frac{1}{1+ae^{j\\omega}} \\)"],"correct":0,"a":"DTFT: \\( (1+ae^{-j\\omega})Y=X \\Rightarrow H=\\frac{1}{1+ae^{-j\\omega}} \\).","fig":""},
{"topic":"dtft","q":"Paralel \\(h_1,h_2\\): \\( H(e^{j\\omega})=\\frac{-12+5e^{-j\\omega}}{12-7e^{-j\\omega}+e^{-2j\\omega}},\\ h_1[n]=(\\frac13)^n u[n] \\). \\( h_2[n]=? \\)","opts":["\\( -2(\\frac14)^n u[n] \\)","\\( 2(\\frac14)^n u[n] \\)","\\( -2(\\frac12)^n u[n] \\)","\\( 2(\\frac12)^n u[n] \\)"],"correct":0,"a":"\\( H=H_1+H_2 \\); kısmi kesir ile \\( H_2=\\frac{-2}{1-\\frac14 e^{-j\\omega}} \\Rightarrow h_2[n]=-2(\\frac14)^n u[n] \\).","fig":""},
{"topic":"dtft","q":"Ters DTFT: \\( X(e^{j\\omega})=\\frac{1-\\frac13 e^{-j\\omega}}{1-\\frac14 e^{-j\\omega}-\\frac18 e^{-2j\\omega}} \\). \\( x[n]=? \\)","opts":["\\( \\frac79(-\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)","\\( \\frac79(-\\frac14)^n u[n]-\\frac29(\\frac12)^n u[n] \\)","\\( \\frac79(\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)","\\( \\frac76(-\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)"],"correct":0,"a":"Payda \\( (1+\\frac14 e^{-j\\omega})(1-\\frac12 e^{-j\\omega}) \\); kısmi kesir \\(A=\\frac79,B=\\frac29\\).","fig":""},
{"topic":"dtft","q":"Kaskad \\(S_1,S_2\\): \\( H(e^{j\\omega})=\\frac{1}{1-\\frac34 e^{-j\\omega}+\\frac18 e^{-2j\\omega}} \\). Dürtü yanıtı \\(h[n]=?\\)","a":"\\( H=\\frac{1}{(1-\\frac12 e^{-j\\omega})(1-\\frac14 e^{-j\\omega})}=\\frac{2}{1-\\frac12 e^{-j\\omega}}-\\frac{1}{1-\\frac14 e^{-j\\omega}} \\Rightarrow h[n]=[2(\\frac12)^n-(\\frac14)^n]u[n] \\).","fig":""},
{"topic":"dtft","q":"Nedensel DT LTI: \\( y[n]-\\frac12 y[n-1]=x[n]+\\frac12 x[n-1] \\). (a) \\(H(\\Omega)\\), (b) \\(h[n]\\), (c) \\(x[n]=\\cos\\frac{\\pi}{2}n\\) için \\(y[n]\\).","a":"(a) \\( H=\\frac{1+\\frac12 e^{-j\\Omega}}{1-\\frac12 e^{-j\\Omega}} \\). (b) \\( h[n]=\\delta[n]+\\,?\\,\\): \\(h[0]=1,\\ h[n]=(\\frac12)^{n-1}\\,(n\\ge1)\\). (c) \\( y[n]=\\cos\\!\\left(\\frac{\\pi}{2}n-2\\tan^{-1}\\frac12\\right) \\).","fig":""},
{"topic":"dtft","q":"Ters sistemin fark denklemi: \\( H_I(e^{j\\Omega})=\\frac{1+2e^{-j\\Omega}}{1+2e^{-j2\\Omega}} \\).","a":"\\( (1+2e^{-j2\\Omega})Y=(1+2e^{-j\\Omega})X \\Rightarrow y[n]+2y[n-2]=x[n]+2x[n-1] \\).","fig":""},
{"topic":"dtft","q":"\\( y[n]=K(-x[n+1]+2x[n]-x[n-1]) \\). (a) \\(H(e^{j\\Omega})\\), (d) \\(\\max|H|=1\\) yapan \\(K\\).","a":"(a) \\( H=K(2-2\\cos\\Omega) \\) (reel, pozitif). (d) Maksimum \\(\\Omega=\\pi\\)'de \\(4K=1\\Rightarrow K=\\frac14\\).","fig":""},

/* ---------- KONVOLÜSYON ---------- */
{"topic":"conv","q":"\\( y(t)=\\frac{d}{dt}\\big(e^{-2(t-1)}u(t-1)\\big)=? \\)","opts":["\\( \\delta(t-1)-2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t-1)+2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t+1)-2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t-1)-2e^{-(t-1)}u(t-1) \\)"],"correct":0,"a":"Çarpım türevi: \\(u\\) türevi \\(\\delta(t-1)\\), üstel türevi \\(-2e^{-2(t-1)}u(t-1)\\).","fig":""},
{"topic":"conv","q":"\\( x(t)=u(t),\\ h(t)=2e^{-(t-4)}u(t-4) \\). Konvolüsyon?","opts":["\\( 2(1-e^{-(t-4)}) \\)","\\( 2(1+e^{-(t-4)}) \\)","\\( 4(1-e^{-(t-4)}) \\)","\\( 2(1-e^{-2(t-4)}) \\)"],"correct":0,"a":"Basamak yanıtı, \\(t>4\\): \\( 2(1-e^{-(t-4)}) \\).","fig":""},
{"topic":"conv","q":"\\( x(t)=1\\ (-1\\le t\\le5),\\ h(t)=(t-1)u(t-1) \\). \\(0\\le t\\le6\\) için \\(y(t)=?\\)","opts":["\\( \\frac12 t^2 \\)","\\( -\\frac12 t^2 \\)","\\( \\frac12 t \\)","\\( \\frac14 t^2 \\)"],"correct":0,"a":"\\( \\int_1^{t+1}(\\tau-1)d\\tau=\\frac12 t^2 \\).","fig":""},
{"topic":"conv","q":"Aynı \\(x,h\\). \\(t>6\\) için \\(y(t)=?\\)","opts":["\\( (6t-18)u(t-6) \\)","\\( (6t-9)u(t+6) \\)","\\( (3t+18)u(t-6) \\)","\\( (3t-18)u(t-6) \\)"],"correct":0,"a":"\\( \\int_{t-5}^{t+1}(\\tau-1)d\\tau=6t-18 \\).","fig":""},
{"topic":"conv","q":"\\( x(t)=2\\delta(t-1)-2\\delta(t-2)+5\\delta(t-4),\\ h(t)=3\\delta(t-3)+2\\delta(t-5) \\). \\(y(t)=?\\)","opts":["\\( 6\\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( \\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( 6\\delta(t-4)+6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( 6\\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)-11\\delta(t-7)+10\\delta(t-9) \\)"],"correct":0,"a":"Her \\(\\delta\\) çiftini kaydır+ölçekle, topla.","fig":""},
{"topic":"conv","q":"\\( x(t)=2\\sin(2\\pi t)\\,\\delta(t-\\frac14),\\ h(t)=2[u(t-2)-u(t-4)] \\). \\(y(t)=?\\)","opts":["\\( 4[u(t-2.25)-u(t-4.25)] \\)","\\( 4[u(t-2.25)+u(t-4.25)] \\)","\\( [u(t-2.25)-u(t-4.25)] \\)","\\( 2[u(t-2.25)-u(t-4.25)] \\)"],"correct":0,"a":"\\( x=2\\sin(\\frac{\\pi}{2})\\delta(t-\\frac14)=2\\delta(t-\\frac14) \\); \\(h\\)'yi \\(\\frac14\\) kaydır, genlik 4.","fig":""},
{"topic":"conv","q":"\\( h[n]=(\\frac23)^n u[n],\\ x[n]=\\delta[n-2] \\). Çıkış?","opts":["\\( \\frac94(\\frac23)^n u[n-2] \\)","\\( \\frac94(\\frac23)^n u[n+2] \\)","\\( \\frac94(\\frac23)^n u[n-1] \\)","\\( \\frac49(\\frac23)^n u[n-2] \\)"],"correct":0,"a":"\\( y[n]=h[n-2]=(\\frac23)^{n-2}u[n-2]=\\frac94(\\frac23)^n u[n-2] \\).","fig":""},
{"topic":"conv","q":"Şekildeki \\(x[n]\\) ve \\(h[n]\\) konvolüsyonu?","opts":["\\(2,6,12,18,14,8\\) (\\(n=1..6\\))","\\(2,4,8,14,12,6\\) (\\(n=1..6\\))","\\(1,4,8,14,12,8\\) (\\(n=0..5\\))","\\(2,6,10,18,14,8\\) (\\(n=1..6\\))"],"correct":0,"a":"Çözüm grafiğinden \\(y[n]=2,6,12,18,14,8\\).","fig":"x[n]: n=0,1,2,3'te yükseklik 1,2,3,4. h[n]: n=0..4'te yükseklik 2."},
{"topic":"conv","q":"\\( y[n]=\\sum_k x[k]g[n-2k],\\ g[n]=u[n]-u[n-4] \\). \\(x[n]=\\delta[n-1]\\) için \\(y[n]=?\\)","a":"\\( y[n]=g[n-2] \\) (yani \\(n=2,3,4,5\\)'te 1).","fig":""},
{"topic":"conv","q":"Aynı sistem, \\(x[n]=u[n]\\) için \\(y[n]=?\\)","a":"\\( y[n]=\\sum_{k\\ge0}g[n-2k]=\\delta[n]+\\delta[n-1]+2u[n-2] \\).","fig":""},

/* ---------- LAPLACE ---------- */
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2},\\ \\mathrm{Re}(s)>-1 \\).","a":"\\( x(t)=(1-e^{-t}-te^{-t})u(t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2},\\ -1<\\mathrm{Re}(s)<0 \\).","a":"\\( x(t)=-u(-t)-(1+t)e^{-t}u(t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2},\\ \\mathrm{Re}(s)<-1 \\).","a":"\\( x(t)=(-1+e^{-t}+te^{-t})u(-t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s+1}{s^2+4s+13},\\ \\mathrm{Re}(s)>-2 \\).","a":"Kareye tamamla \\((s+2)^2+9\\): \\( x(t)=e^{-2t}(\\cos 3t-\\frac13\\sin 3t)u(t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s}{(s^2+4)^2},\\ \\mathrm{Re}(s)>0 \\).","a":"\\( x(t)=\\frac14 t\\sin 2t\\,u(t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s}{s^3+2s^2+9s+18},\\ \\mathrm{Re}(s)>-2 \\).","a":"\\( s^3+2s^2+9s+18=(s+2)(s^2+9) \\): \\( x(t)=(-\\frac{2}{13}e^{-2t}+\\frac{2}{13}\\cos 3t+\\frac{3}{13}\\sin 3t)u(t) \\).","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{5s+13}{s(s^2+4s+13)},\\ \\mathrm{Re}(s)>0 \\).","a":"\\( \\frac1s-\\frac{s+2}{(s+2)^2+9}+\\frac{3}{(s+2)^2+9} \\Rightarrow x(t)=[1-e^{-2t}(\\cos 3t-\\sin 3t)]u(t) \\).","fig":""},
{"topic":"laplace","q":"Laplace: \\( x(t)=(e^{-t}\\cos 2t-5e^{-2t})u(t)+\\frac12 e^{2t}u(-t) \\).","a":"\\( X(s)=\\frac{s+1}{(s+1)^2+4}-\\frac{5}{s+2}-\\frac12\\frac{1}{s-2},\\ -1<\\mathrm{Re}(s)<2 \\).","fig":""},
{"topic":"laplace","q":"CT LTI: \\(x(t)=u(t)\\Rightarrow y(t)=2e^{-3t}u(t)\\). (a) \\(h(t)\\), (b) \\(x=e^{-t}u(t)\\) için \\(y(t)\\).","a":"(a) \\( H(s)=\\frac{2s}{s+3}=2-\\frac{6}{s+3}\\Rightarrow h(t)=2\\delta(t)-6e^{-3t}u(t) \\). (b) \\( Y=\\frac{2s}{(s+1)(s+3)}=-\\frac{1}{s+1}+\\frac{3}{s+3}\\Rightarrow y(t)=(-e^{-t}+3e^{-3t})u(t) \\).","fig":""},
{"topic":"laplace","q":"\\( y''+y'-2y=x \\). (a) \\(H(s)\\), (b) \\(h(t)\\): (i) nedensel (ii) kararlı (iii) hiçbiri.","a":"\\( H=\\frac{1}{(s+2)(s-1)}=-\\frac13\\frac{1}{s+2}+\\frac13\\frac{1}{s-1} \\). (i) \\(\\frac13(e^{t}-e^{-2t})u(t)\\). (ii) \\(-\\frac13 e^{-2t}u(t)-\\frac13 e^{t}u(-t)\\). (iii) \\(\\frac13(e^{-2t}-e^{t})u(-t)\\).","fig":""},
{"topic":"laplace","q":"Nedensel sistem: \\( y'(t)+2y(t)=x(t)+x'(t) \\). Dürtü yanıtı \\(h(t)=?\\)","a":"\\( H(s)=\\frac{s+1}{s+2}=1-\\frac{1}{s+2}\\Rightarrow h(t)=\\delta(t)-e^{-2t}u(t) \\).","fig":""},

/* ---------- Z-DÖNÜŞÜMÜ ---------- */
{"topic":"z","q":"Z-dönüşümü: (a) \\(x[n]=-a^n u[-n-1]\\), (b) \\(x[n]=a^{-n}u[-n-1]\\).","a":"(a) \\( X(z)=\\frac{1}{1-az^{-1}}=\\frac{z}{z-a},\\ |z|<|a| \\). (b) \\( X(z)=-\\frac{z}{z-1/a},\\ |z|<\\frac{1}{|a|} \\).","fig":""},
{"topic":"z","q":"Z-dönüşümü + kutup-sıfır: \\( x[n]=(\\frac12)^n u[n]+(\\frac13)^n u[n] \\).","a":"\\( X(z)=\\frac{2z(z-\\frac{5}{12})}{(z-\\frac12)(z-\\frac13)},\\ |z|>\\frac12 \\). Sıfırlar \\(0,\\frac{5}{12}\\); kutuplar \\(\\frac12,\\frac13\\).","fig":"ROC: |z|>1/2 (en dış kutbun dışı)."},
{"topic":"z","q":"Z-dönüşümü + kutup-sıfır: \\( x[n]=(\\frac13)^n u[n]-(\\frac12)^n u[-n-1] \\).","a":"\\( X(z)=-\\frac16\\frac{z}{(z-\\frac12)(z-\\frac13)},\\ \\frac13<|z|<\\frac12 \\). Sıfır \\(z=0\\); kutuplar \\(\\frac12,\\frac13\\).","fig":"ROC: halka 1/3<|z|<1/2 (biri sağ, biri sol taraflı)."},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{3}{z-2},\\ |z|>2 \\).","a":"\\( X=3z^{-1}\\frac{z}{z-2}\\Rightarrow x[n]=3\\cdot 2^{n-1}u[n-1] \\).","fig":""},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{2+z^{-2}+3z^{-4}}{z^2+4z+3},\\ |z|>0 \\).","a":"\\( X_1=\\frac{z}{z^2+4z+3}\\Rightarrow x_1[n]=\\frac12[(-1)^n-(-3)^n]u[n] \\); \\( x[n]=2x_1[n-1]+x_1[n-3]+3x_1[n-5] \\).","fig":""},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{1}{(1-az^{-1})^2},\\ |z|>|a| \\).","a":"\\( x[n]=(n+1)a^n u[n] \\).","fig":""},
{"topic":"z","q":"Blok diyagramlı nedensel sistem: \\( y[n]-\\frac32 y[n-1]+\\frac12 y[n-2]=x[n]-x[n-2] \\). (b) BIBO kararlı mı? (c) \\(x[n]=(-1)^n u[n]\\), \\(y[-1]=y[-2]=1\\) için çıkış.","a":"\\( H(z)=\\frac{1+z^{-1}}{1-\\frac12 z^{-1}} \\) (kutup \\(z=\\frac12\\) içeride \\(\\Rightarrow\\) kararlı). \\( y[n]=(1+(\\frac12)^n)u[n] \\).","fig":""},

/* ---------- SİSTEM / SİNYAL ÖZELLİKLERİ ---------- */
{"topic":"sys","q":"\\( y(t)=x(t/2)+x(t+4) \\). Nedensellik, kararlılık, doğrusallık, zamanla değişmezlik, hafıza?","a":"Nedensel değil (gelecek değer kullanır); kararlı; doğrusal; zamanla değişmez DEĞİL (\\(x(t/2)\\) ölçekleme); hafızalı.","fig":""},
{"topic":"sys","q":"\\( y[n]=2(\\frac12)^n x[n] \\). Doğrusal ve/veya zamanla değişmez mi?","a":"Doğrusal (üst üste binme sağlanır). Zamanla değişmez DEĞİL: katsayı \\(n\\)'e bağlı.","fig":""},
{"topic":"sys","q":"\\( h(t)=e^{-(t-1)}u(t-1) \\). (b) Nedensel mi? (c) Kararlı mı? (d-e) \\(x(t)=u(t+2)\\) için \\(t_1\\) ve \\(y(t)\\).","a":"Nedensel (\\(h=0,\\ t<1\\)); kararlı (\\(\\int_1^\\infty e^{-(t-1)}dt=1\\)); \\(t_1=-1\\); \\(t>-1\\) için \\(y(t)=1-e^{-(t+1)}\\).","fig":""},
{"topic":"sys","q":"\\( h(t)=e^{-2t}\\) (\\(-1<t<1\\), dışında 0). Nedensel mi, kararlı mı? \\(x(t)=\\delta(t+5)\\) için \\(y(t)\\)?","a":"Nedensel değil (\\(t<0\\)'da \\(h\\neq0\\)); kararlı (\\(\\int_{-1}^{1}e^{-2t}dt<\\infty\\)); \\( y(t)=h(t+5)=e^{-2(t+5)},\\ -6<t<-4 \\).","fig":""},
{"topic":"sys","q":"Periyodiklik: (a) \\(x[n]=\\cos(n/4)\\) (b) \\(x[n]=e^{j7\\pi n/12}\\) (c) \\(x[n]=\\frac{3\\sin(\\pi n/3)}{\\pi n}\\).","a":"(a) Periyodik değil (\\(N=8\\pi\\) tam sayı değil). (b) Periyodik, \\(N=24\\). (c) Periyodik değil.","fig":""},
{"topic":"sys","q":"Hangi ifade YANLIŞ? A) \\(\\delta[n]=u[n-1]-u[n]\\) B) \\(\\delta[n]=u[n]-u[n-1]\\) C) \\(u[n]=\\sum_{k\\ge0}\\delta[n-k]\\) D) \\(x[n]\\delta[n-n_0]=x[n_0]\\delta[n-n_0]\\) E) \\(\\delta(t)=\\frac{du}{dt}\\)","opts":["A","B","C","D"],"correct":0,"a":"A yanlış; doğrusu \\(\\delta[n]=u[n]-u[n-1]\\) (işaret ters).","fig":""},
{"topic":"sys","q":"\\(t\\ge3\\)'te yükseklik 4, \\(t<3\\)'te 0 olan sinyal hangisi?","opts":["\\( 4u(t-3) \\)","\\( 4u(t+3) \\)","\\( 4u(3-t) \\)","\\( 4\\delta(t-3) \\)"],"correct":0,"a":"Kaydırılmış basamak.","fig":""},
{"topic":"sys","q":"\\(1\\le t\\le4\\)'te yükseklik \\(-1\\), dışında 0 olan sinyal?","opts":["\\( u(t-4)-u(t-1) \\)","\\( u(t-1)-u(t-4) \\)","\\( -u(t+1)+u(t+4) \\)","\\( u(1-t)-u(4-t) \\)"],"correct":0,"a":"\\( -[u(t-1)-u(t-4)]=u(t-4)-u(t-1) \\).","fig":""},
{"topic":"sys","q":"\\(2\\le t\\le6\\)'da yükseklik 3 olan \\(h(t)\\)?","opts":["\\( 3u(t-2)-3u(t-6) \\)","\\( 3u(t-6)-3u(t-2) \\)","\\( 3u(t-2)+3u(t-6) \\)","\\( 3\\delta(t-2)-3\\delta(t-6) \\)"],"correct":0,"a":"Dikdörtgen darbe.","fig":""},
{"topic":"sys","q":"LTI \\( h(t)=e^{-(t-1)}u(t-1) \\). (A) Otokorelasyon \\(R_h(\\tau)\\), (B) Enerji \\(E_h\\).","a":"\\( R_h(\\tau)=\\frac12(e^{\\tau}u(-\\tau)+e^{-\\tau}u(\\tau)) \\); \\( E_h=R_h(0)=\\frac12 \\).","fig":""},

/* ---------- ÖRNEKLEME / MODÜLASYON ---------- */
{"topic":"sampling","q":"\\(T_s=0.001s\\) (1kHz), ideal alçak-geçiren \\(|H|=1,\\ |\\Omega|<\\pi/2\\), faz \\(-2\\Omega\\). \\(x(t)=1-\\cos(300\\pi t)+3\\sin(600\\pi t)\\) için \\(y[n]=?\\)","a":"\\( x[n]=1-\\cos(0.3\\pi n)+3\\sin(0.6\\pi n) \\). \\(0.6\\pi>\\pi/2\\) bileşeni süzülür: \\( y[n]=1-\\cos(0.3\\pi(n-2)) \\).","fig":""},
{"topic":"sampling","q":"İdeal LPF (kesim \\(\\pi/2\\), gecikme 2) için dürtü yanıtı \\(h[n]=?\\)","a":"\\( h[n]=\\frac{1}{2\\pi}\\int_{-\\pi/2}^{\\pi/2}e^{j\\Omega(n-2)}d\\Omega=\\frac{\\sin[\\frac{\\pi}{2}(n-2)]}{\\pi(n-2)} \\).","fig":""}

];
