/* ============================================================
   SORU BANKASI — tüm PDF kaynaklarından derlenen sorular + DETAYLI çözümler
   Math: \( \) inline, \[ \] display.  Çözümler .step blokları halinde.
   Alanlar: topic, q, opts?, correct?, a(detaylı çözüm HTML), fig?
   ============================================================ */
const QBANK = [

/* ---------- FOURIER DÖNÜŞÜMÜ ---------- */
{"topic":"fourier","q":"\\( f(t)=\\begin{cases}3 & -2\\le t\\le 2\\\\ 0 & \\text{diğer}\\end{cases} \\). Fourier dönüşümü?","opts":["\\( \\frac{6}{\\omega}\\sin 2\\omega \\)","\\( -\\frac{6}{\\omega}\\sin 2\\omega \\)","\\( \\frac{6}{\\omega}\\sin 4\\omega \\)","\\( \\frac{6}{\\omega}\\cos 2\\omega \\)"],"correct":0,"a":"<div class='step'><b>1) Tanımı yaz.</b> \\(f(t)\\) sadece \\([-2,2]\\)'de \\(3\\): \\[X(j\\omega)=\\int_{-2}^{2}3e^{-j\\omega t}\\,dt.\\]</div><div class='step'><b>2) İntegre et.</b> \\[=3\\cdot\\frac{e^{-j\\omega t}}{-j\\omega}\\Big|_{-2}^{2}=\\frac{3}{-j\\omega}\\big(e^{-j2\\omega}-e^{j2\\omega}\\big).\\]</div><div class='step'><b>3) Euler.</b> \\(e^{-j2\\omega}-e^{j2\\omega}=-2j\\sin 2\\omega\\), dolayısıyla \\[X(j\\omega)=\\frac{3}{-j\\omega}(-2j\\sin2\\omega)=\\frac{6}{\\omega}\\sin2\\omega.\\] Kısa yol: genişlik \\(2T=4\\,(T=2)\\), yükseklik \\(A=3\\) dikdörtgen \\(\\Rightarrow \\frac{2A}{\\omega}\\sin(\\omega T)\\).</div>","fig":""},
{"topic":"fourier","q":"\\( x(t)=e^{-at^2},\\ a>0 \\) (Gauss). \\( X(j\\omega)=? \\)","opts":["\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4a} \\)","\\( -\\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4a} \\)","\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^4/4a} \\)","\\( \\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4} \\)"],"correct":0,"a":"<div class='step'><b>1) İntegral + kareye tamamlama.</b> \\[X=\\int_{-\\infty}^{\\infty}e^{-at^2}e^{-j\\omega t}dt=\\int e^{-a\\left(t+\\frac{j\\omega}{2a}\\right)^2}dt\\;e^{-\\omega^2/4a}.\\] Üstelde \\(-at^2-j\\omega t=-a(t+\\frac{j\\omega}{2a})^2-\\frac{\\omega^2}{4a}\\).</div><div class='step'><b>2) Gauss integrali.</b> \\(\\int e^{-a u^2}du=\\sqrt{\\pi/a}\\). Sonuç: \\[X(j\\omega)=\\sqrt{\\frac{\\pi}{a}}\\,e^{-\\omega^2/4a}.\\] Gauss'un dönüşümü yine Gauss'tur.</div>","fig":""},
{"topic":"fourier","q":"\\( x(t)=\\begin{cases}1 & -a\\le t\\le a\\\\ 0 & \\text{diğer}\\end{cases} \\). \\( X(j\\omega)=? \\)","opts":["\\( 2a\\,\\mathrm{sinc}(\\omega a) \\)","\\( 2a\\,\\mathrm{sinc}(\\omega) \\)","\\( 2\\,\\mathrm{sinc}(\\omega a) \\)","\\( 4a\\,\\mathrm{sinc}(\\omega a) \\)"],"correct":0,"a":"<div class='step'><b>1) İntegral.</b> \\[X=\\int_{-a}^{a}e^{-j\\omega t}dt=\\frac{e^{-j\\omega t}}{-j\\omega}\\Big|_{-a}^{a}=\\frac{2\\sin(\\omega a)}{\\omega}.\\]</div><div class='step'><b>2) sinc biçimi.</b> \\(\\mathrm{sinc}(x)=\\frac{\\sin x}{x}\\) ile \\[X=\\frac{2\\sin(\\omega a)}{\\omega}=2a\\,\\frac{\\sin(\\omega a)}{\\omega a}=2a\\,\\mathrm{sinc}(\\omega a).\\] Genişlik \\(2a\\), yükseklik \\(1\\).</div>","fig":""},
{"topic":"fourier","q":"\\( x(t)=\\begin{cases}e^{-at} & t\\ge 0\\\\ e^{at} & t<0\\end{cases}=e^{-a|t|} \\). \\( X(j\\omega)=? \\)","opts":["\\( \\frac{2a}{a^2+\\omega^2} \\)","\\( \\frac{2a}{a^2-\\omega^2} \\)","\\( \\frac{a}{a^2+\\omega^2} \\)","\\( \\frac{1}{a+j\\omega} \\)"],"correct":0,"a":"<div class='step'><b>1) İkiye böl.</b> \\[X=\\int_{-\\infty}^{0}e^{at}e^{-j\\omega t}dt+\\int_{0}^{\\infty}e^{-at}e^{-j\\omega t}dt.\\]</div><div class='step'><b>2) Her parça.</b> \\[=\\frac{1}{a-j\\omega}+\\frac{1}{a+j\\omega}=\\frac{2a}{a^2+\\omega^2}.\\] (Standart FT tanımı \\(X(j\\omega)=\\int x(t)e^{-j\\omega t}dt\\) ile.)</div>","fig":""},
{"topic":"fourier","q":"Üç birim impuls: \\(t=-4,0,+4\\)'te yükseklik 1. \\( X(j\\omega)=? \\)","opts":["\\( 1+2\\cos(4\\omega) \\)","\\( 1-2\\cos(4\\omega) \\)","\\( 1+2\\cos(2\\omega) \\)","\\( 1+2\\sin(4\\omega) \\)"],"correct":0,"a":"<div class='step'><b>1) Impuls dönüşümü.</b> \\(\\delta(t-t_0)\\leftrightarrow e^{-j\\omega t_0}\\). \\(x(t)=\\delta(t+4)+\\delta(t)+\\delta(t-4)\\) için \\[X=e^{j4\\omega}+1+e^{-j4\\omega}.\\]</div><div class='step'><b>2) Topla.</b> \\(e^{j4\\omega}+e^{-j4\\omega}=2\\cos4\\omega\\Rightarrow X=1+2\\cos(4\\omega).\\)</div>","fig":"x(t): t=-4, 0, +4 noktalarında yükseklik 1 olan birim impulslar."},
{"topic":"fourier","q":"\\( x(t)=e^{-2t+4}\\,u(t-2) \\). \\( X(j\\omega)=? \\)","opts":["\\( \\frac{e^{-2j\\omega}}{j\\omega+2} \\)","\\( \\frac{e^{-2j\\omega}}{j\\omega-2} \\)","\\( \\frac{e^{-j\\omega}}{j\\omega+2} \\)","\\( \\frac{e^{-2j\\omega}}{\\omega+2} \\)"],"correct":0,"a":"<div class='step'><b>1) Kaydırılmış biçime sok.</b> \\(-2t+4=-2(t-2)\\) olduğundan \\[x(t)=e^{-2(t-2)}u(t-2).\\]</div><div class='step'><b>2) Temel çift + kayma.</b> \\(e^{-2t}u(t)\\leftrightarrow\\frac{1}{j\\omega+2}\\). \\(t\\to t-2\\) kayması \\(\\times e^{-j2\\omega}\\): \\[X(j\\omega)=\\frac{e^{-2j\\omega}}{j\\omega+2}.\\]</div>","fig":""},
{"topic":"fourier","q":"\\( x(t)=e^{-at}u(t),\\ a>0 \\). Sürekli Fourier dönüşümü?","opts":["\\( \\frac{1}{a+j\\omega} \\)","\\( \\frac{1}{a-j\\omega} \\)","\\( \\frac{1}{2a+j\\omega} \\)","\\( \\frac{1}{a^2+j\\omega^2} \\)"],"correct":0,"a":"<div class='step'><b>1) İntegral.</b> \\[X=\\int_{0}^{\\infty}e^{-at}e^{-j\\omega t}dt=\\int_{0}^{\\infty}e^{-(a+j\\omega)t}dt.\\]</div><div class='step'><b>2) Sonuç.</b> \\(a>0\\) yakınsaklığı verir: \\[=\\frac{1}{a+j\\omega}.\\] En çok kullanılan temel çifttir.</div>","fig":""},
{"topic":"fourier","q":"Ters Fourier: \\( X(j\\omega)=1 \\) (yalnız \\(\\pi\\le|\\omega|\\le 2\\pi\\)'de). \\( x(t)=? \\)","a":"<div class='step'><b>1) Ters dönüşüm.</b> \\[x(t)=\\frac{1}{2\\pi}\\Big(\\int_{\\pi}^{2\\pi}+\\int_{-2\\pi}^{-\\pi}\\Big)e^{j\\omega t}d\\omega.\\]</div><div class='step'><b>2) Simetriyi kullan.</b> İki bant çifttir; toplam \\[=\\frac{1}{\\pi t}\\big(\\sin 2\\pi t-\\sin\\pi t\\big).\\]</div><div class='step'><b>3) sinc biçimi.</b> \\(\\mathrm{sinc}(t)=\\frac{\\sin\\pi t}{\\pi t}\\) ile \\[x(t)=2\\,\\mathrm{sinc}(2t)-\\mathrm{sinc}(t).\\]</div>","fig":"X(jw): [-2π,-π] ve [π,2π] aralıklarında yükseklik 1, dışında 0."},
{"topic":"fourier","q":"Frekans yanıtı yöntemiyle: \\( y(t)=\\int_{-\\infty}^{\\infty}e^{-\\tau}u(\\tau)\\,3\\cos(t-\\tau-\\pi)\\,d\\tau=? \\)","a":"<div class='step'><b>1) Konvolüsyon olarak gör.</b> İntegral \\(h*x\\) biçimindedir; \\(h(t)=e^{-t}u(t)\\), \\(x(t)=3\\cos(t-\\pi)\\) (\\(\\omega_0=1\\)).</div><div class='step'><b>2) Özfonksiyon özelliği.</b> LTI sistemde \\(\\cos(\\omega_0 t+\\phi)\\to|H(j\\omega_0)|\\cos(\\omega_0 t+\\phi+\\angle H)\\). \\[H(j1)=\\frac{1}{1+j}=\\frac{1}{\\sqrt2}\\,e^{-j\\pi/4}.\\]</div><div class='step'><b>3) Uygula.</b> Genlik \\(3\\cdot\\frac{1}{\\sqrt2}=\\frac{3}{\\sqrt2}\\approx2{,}12\\), faz \\(-\\frac{\\pi}{4}\\): \\[y(t)=\\frac{3}{\\sqrt2}\\cos\\!\\big(t-\\pi-\\tfrac{\\pi}{4}\\big).\\]</div>","fig":""},
{"topic":"fourier","q":"Frekans yanıtı yöntemiyle: \\( y(t)=\\int_{-\\infty}^{\\infty}e^{\\tau}u(-\\tau)\\,2\\cos(t-\\tau+\\pi)\\,d\\tau \\).","a":"<div class='step'><b>1) Sistem.</b> \\(h(t)=e^{t}u(-t)\\) (anti-nedensel), \\(x(t)=2\\cos(t+\\pi)\\).</div><div class='step'><b>2) Frekans yanıtı.</b> \\[H(j\\omega)=\\int_{-\\infty}^{0}e^{t}e^{-j\\omega t}dt=\\frac{1}{1-j\\omega}.\\] \\(H(j1)=\\frac{1}{1-j}=\\frac{1}{\\sqrt2}e^{+j\\pi/4}\\).</div><div class='step'><b>3) Uygula.</b> Genlik \\(2\\cdot\\frac{1}{\\sqrt2}=\\sqrt2\\), faz \\((t+\\pi)+\\frac{\\pi}{4}=t+\\frac{5\\pi}{4}\\equiv t-\\frac{3\\pi}{4}\\): \\[y(t)=\\sqrt2\\,\\cos\\!\\big(t-\\tfrac{3\\pi}{4}\\big).\\]</div>","fig":""},

/* ---------- FOURIER SERİSİ ---------- */
{"topic":"fseries","q":"\\( x(t) \\) periyodu \\(T=3\\): \\( 3\\ (0\\le t<1.5),\\ -3\\ (1.5\\le t<3) \\). Fourier seri katsayısı \\(a_k=?\\)","opts":["\\( \\frac{6}{k\\pi}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( -\\frac{6}{k\\pi}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( \\frac{6}{k}\\sin(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)","\\( \\frac{6}{k\\pi}\\cos(\\frac{k\\pi}{2})e^{-jk\\pi/2} \\)"],"correct":0,"a":"<div class='step'><b>1) Tanım.</b> \\(\\omega_0=\\frac{2\\pi}{T}=\\frac{2\\pi}{3}\\), \\[a_k=\\frac{1}{3}\\Big[\\int_{0}^{1.5}3e^{-jk\\omega_0 t}dt+\\int_{1.5}^{3}(-3)e^{-jk\\omega_0 t}dt\\Big].\\]</div><div class='step'><b>2) İntegralleri al ve sadeleştir.</b> Üsteller toplanınca ortak çarpan \\(e^{-jk\\pi/2}\\) çıkar; sinüs terimi \\(\\sin(\\frac{k\\pi}{2})\\) verir: \\[a_k=\\frac{6}{k\\pi}\\sin\\!\\Big(\\frac{k\\pi}{2}\\Big)e^{-jk\\pi/2}.\\]</div><div class='step'><b>Not:</b> Kare dalga olduğundan tek \\(k\\)'lerde \\(\\sin(\\frac{k\\pi}{2})=\\pm1\\), çift \\(k\\)'lerde \\(0\\).</div>","fig":""},
{"topic":"fseries","q":"\\( x(t)=10\\cos(\\omega_0 t-\\frac{13\\pi}{2})+7\\cos(\\omega_0 t+\\frac{3\\pi}{4})+7\\cos(\\omega_0 t+\\frac{5\\pi}{4}) \\) ifadesini \\(A\\cos(\\omega_0 t+\\phi)\\) yap.","a":"<div class='step'><b>1) Fazörlere geç.</b> Her terim \\(A_i e^{j\\phi_i}\\). \\(e^{-j13\\pi/2}=e^{-j\\pi/2}=-j\\Rightarrow 10\\to -10j\\).</div><div class='step'><b>2) Diğer ikisi.</b> \\(7e^{j3\\pi/4}+7e^{j5\\pi/4}=7(-\\tfrac{\\sqrt2}{2}+j\\tfrac{\\sqrt2}{2})+7(-\\tfrac{\\sqrt2}{2}-j\\tfrac{\\sqrt2}{2})=-7\\sqrt2\\) (sanal kısımlar yok olur).</div><div class='step'><b>3) Topla.</b> \\(P=-7\\sqrt2-10j\\Rightarrow |P|=\\sqrt{98+100}=\\sqrt{198}\\approx14{,}07\\), \\(\\angle P\\approx-0{,}748\\pi\\). \\[x(t)\\approx 14{,}07\\cos(\\omega_0 t-0{,}748\\pi).\\]</div>","fig":""},
{"topic":"fseries","q":"\\( x(t)=\\sum_{k=-2}^{2}\\frac{1}{1+jk}e^{jkt} \\) sinyalini sinüzoidal biçimde yaz.","a":"<div class='step'><b>1) Katsayılar.</b> \\(a_k=\\frac{1}{1+jk}\\): \\(a_0=1\\), \\(a_1=\\frac{1}{\\sqrt2}e^{-j\\pi/4}\\), \\(a_2=\\frac{1}{\\sqrt5}e^{-j\\arctan 2}\\). \\(a_{-k}=a_k^*\\) (sinyal reel).</div><div class='step'><b>2) Reel forma topla.</b> \\(x(t)=a_0+2\\sum_{k\\ge1}|a_k|\\cos(kt+\\angle a_k)\\): \\[x(t)=1+\\tfrac{2}{\\sqrt2}\\cos\\!\\big(t-\\tfrac{\\pi}{4}\\big)+\\tfrac{2}{\\sqrt5}\\cos\\!\\big(2t-0{,}352\\pi\\big).\\]</div>","fig":""},
{"topic":"fseries","q":"\\( x(t)=\\sum_{k=-3}^{3}\\frac{1}{1-jk}e^{-jkt} \\) sinyalini sinüzoidal biçimde yaz.","a":"<div class='step'><b>1) Değişken değiştir.</b> \\(m=-k\\) ile \\(x(t)=\\sum_m\\frac{1}{1+jm}e^{jmt}\\) (bir önceki soruyla aynı yapı, \\(\\pm3\\) terimi eklenmiş).</div><div class='step'><b>2) Reel form.</b> \\(|a_k|=\\frac{1}{\\sqrt{1+k^2}}\\), \\(\\angle a_k=-\\arctan k\\): \\[x(t)=1+\\tfrac{2}{\\sqrt2}\\cos(t-\\tfrac{\\pi}{4})+\\tfrac{2}{\\sqrt5}\\cos(2t-0{,}352\\pi)+\\tfrac{2}{\\sqrt{10}}\\cos(3t-0{,}398\\pi).\\]</div>","fig":""},

/* ---------- DTFT / FREKANS YANITI ---------- */
{"topic":"dtft","q":"\\( x[n]=\\delta[n+2]-\\delta[n-2] \\). \\( X(e^{j\\omega})=? \\)","opts":["\\( 2j\\sin(2\\omega) \\)","\\( 2j\\cos(2\\omega) \\)","\\( 2j\\sin(4\\omega) \\)","\\( 2\\sin(2\\omega) \\)"],"correct":0,"a":"<div class='step'><b>1) Çift uygula.</b> \\(\\delta[n-n_0]\\leftrightarrow e^{-j\\omega n_0}\\): \\[X=e^{j2\\omega}-e^{-j2\\omega}.\\]</div><div class='step'><b>2) Euler.</b> \\(e^{j2\\omega}-e^{-j2\\omega}=2j\\sin(2\\omega).\\)</div>","fig":""},
{"topic":"dtft","q":"LZD sistem: \\( ay[n-1]+y[n]=x[n] \\). \\( H(e^{j\\omega})=? \\)","opts":["\\( \\frac{1}{1+ae^{-j\\omega}} \\)","\\( \\frac{1}{1-ae^{-j\\omega}} \\)","\\( \\frac{1}{2+ae^{-j\\omega}} \\)","\\( \\frac{1}{1+ae^{j\\omega}} \\)"],"correct":0,"a":"<div class='step'><b>1) DTFT al.</b> \\(y[n-1]\\to e^{-j\\omega}Y\\): \\[ae^{-j\\omega}Y+Y=X\\Rightarrow Y(1+ae^{-j\\omega})=X.\\]</div><div class='step'><b>2) Oranı çek.</b> \\[H(e^{j\\omega})=\\frac{Y}{X}=\\frac{1}{1+ae^{-j\\omega}}.\\]</div>","fig":""},
{"topic":"dtft","q":"Paralel \\(h_1,h_2\\): \\( H(e^{j\\omega})=\\frac{-12+5e^{-j\\omega}}{12-7e^{-j\\omega}+e^{-2j\\omega}},\\ h_1[n]=(\\frac13)^n u[n] \\). \\( h_2[n]=? \\)","opts":["\\( -2(\\frac14)^n u[n] \\)","\\( 2(\\frac14)^n u[n] \\)","\\( -2(\\frac12)^n u[n] \\)","\\( 2(\\frac12)^n u[n] \\)"],"correct":0,"a":"<div class='step'><b>1) Paydayı çarpanla.</b> \\(r=e^{-j\\omega}\\); \\(r^2-7r+12=(r-3)(r-4)\\). Pay/payda kısmi kesir: \\[H=\\frac{-3}{r-3}+\\frac{8}{r-4}.\\]</div><div class='step'><b>2) Standart biçime getir.</b> \\(\\frac{-3}{r-3}=\\frac{1}{1-\\frac13 r}=H_1\\) (\\(h_1=(\\frac13)^n u[n]\\) doğrulanır). \\(\\frac{8}{r-4}=\\frac{-2}{1-\\frac14 r}=H_2\\).</div><div class='step'><b>3) Sonuç.</b> Paralelde \\(H=H_1+H_2\\Rightarrow h_2[n]=-2(\\tfrac14)^n u[n].\\)</div>","fig":""},
{"topic":"dtft","q":"Ters DTFT: \\( X(e^{j\\omega})=\\frac{1-\\frac13 e^{-j\\omega}}{1-\\frac14 e^{-j\\omega}-\\frac18 e^{-2j\\omega}} \\). \\( x[n]=? \\)","opts":["\\( \\frac79(-\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)","\\( \\frac79(-\\frac14)^n u[n]-\\frac29(\\frac12)^n u[n] \\)","\\( \\frac79(\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)","\\( \\frac76(-\\frac14)^n u[n]+\\frac29(\\frac12)^n u[n] \\)"],"correct":0,"a":"<div class='step'><b>1) Paydayı çarpanla.</b> \\(r=e^{-j\\omega}\\); \\(1-\\frac14 r-\\frac18 r^2=(1-\\tfrac12 r)(1+\\tfrac14 r)\\).</div><div class='step'><b>2) Kısmi kesir.</b> \\[X=\\frac{A}{1-\\frac12 r}+\\frac{B}{1+\\frac14 r}.\\] \\(A=\\frac{1-\\frac13 r}{1+\\frac14 r}\\big|_{r=2}=\\frac{1/3}{3/2}=\\frac29\\); \\(B=\\frac{1-\\frac13 r}{1-\\frac12 r}\\big|_{r=-4}=\\frac{7/3}{3}=\\frac79\\).</div><div class='step'><b>3) Ters al.</b> \\[x[n]=\\tfrac79(-\\tfrac14)^n u[n]+\\tfrac29(\\tfrac12)^n u[n].\\]</div>","fig":""},
{"topic":"dtft","q":"Kaskad \\(S_1,S_2\\): \\( H(e^{j\\omega})=\\frac{1}{1-\\frac34 e^{-j\\omega}+\\frac18 e^{-2j\\omega}} \\). Dürtü yanıtı \\(h[n]=?\\)","a":"<div class='step'><b>1) Çarpanla.</b> \\(1-\\frac34 r+\\frac18 r^2=(1-\\tfrac12 r)(1-\\tfrac14 r)\\), \\(r=e^{-j\\omega}\\).</div><div class='step'><b>2) Kısmi kesir.</b> \\[H=\\frac{2}{1-\\frac12 r}-\\frac{1}{1-\\frac14 r}.\\]</div><div class='step'><b>3) Ters DTFT.</b> \\[h[n]=\\big[2(\\tfrac12)^n-(\\tfrac14)^n\\big]u[n].\\]</div>","fig":""},
{"topic":"dtft","q":"Nedensel DT LTI: \\( y[n]-\\frac12 y[n-1]=x[n]+\\frac12 x[n-1] \\). (a) \\(H\\), (b) \\(h[n]\\), (c) \\(x[n]=\\cos\\frac{\\pi}{2}n\\) için \\(y[n]\\).","a":"<div class='step'><b>(a) DTFT.</b> \\[H=\\frac{1+\\frac12 e^{-j\\Omega}}{1-\\frac12 e^{-j\\Omega}}.\\]</div><div class='step'><b>(b) \\(h[n]\\).</b> \\(H=-1+\\frac{2}{1-\\frac12 e^{-j\\Omega}}\\Rightarrow h[n]=-\\delta[n]+2(\\tfrac12)^n u[n]\\); yani \\(h[0]=1\\), \\(h[n]=(\\tfrac12)^{\\,n-1}\\ (n\\ge1)\\).</div><div class='step'><b>(c) Sinüse yanıt.</b> \\(\\Omega=\\frac{\\pi}{2}\\Rightarrow e^{-j\\pi/2}=-j\\). \\(H=\\frac{1-\\frac{j}{2}}{1+\\frac{j}{2}}\\): \\(|H|=1\\), \\(\\angle H=-2\\tan^{-1}\\frac12\\). \\[y[n]=\\cos\\!\\big(\\tfrac{\\pi}{2}n-2\\tan^{-1}\\tfrac12\\big).\\]</div>","fig":""},
{"topic":"dtft","q":"Ters sistemin fark denklemini yaz: \\( H_I(e^{j\\Omega})=\\frac{1+2e^{-j\\Omega}}{1+2e^{-j2\\Omega}} \\).","a":"<div class='step'><b>1) Oranı aç.</b> \\(\\frac{Y}{X}=H_I\\Rightarrow Y(1+2e^{-j2\\Omega})=X(1+2e^{-j\\Omega}).\\)</div><div class='step'><b>2) Zaman bölgesine dön.</b> \\(e^{-jk\\Omega}\\to\\) gecikme \\(k\\): \\[y[n]+2y[n-2]=x[n]+2x[n-1].\\]</div>","fig":""},
{"topic":"dtft","q":"\\( y[n]=K(-x[n+1]+2x[n]-x[n-1]) \\). (a) \\(H(e^{j\\Omega})\\), (d) \\(\\max|H|=1\\) yapan \\(K\\).","a":"<div class='step'><b>(a)</b> \\(H=K(-e^{j\\Omega}+2-e^{-j\\Omega})=K(2-2\\cos\\Omega)\\); reel ve \\(\\ge0\\).</div><div class='step'><b>(d)</b> \\(2-2\\cos\\Omega\\) en büyük \\(\\Omega=\\pi\\)'de: \\(2-2(-1)=4\\). \\(4K=1\\Rightarrow K=\\tfrac14.\\)</div>","fig":""},

/* ---------- KONVOLÜSYON ---------- */
{"topic":"conv","q":"\\( y(t)=\\frac{d}{dt}\\big(e^{-2(t-1)}u(t-1)\\big)=? \\)","opts":["\\( \\delta(t-1)-2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t-1)+2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t+1)-2e^{-2(t-1)}u(t-1) \\)","\\( \\delta(t-1)-2e^{-(t-1)}u(t-1) \\)"],"correct":0,"a":"<div class='step'><b>1) Çarpım türevi.</b> \\(\\frac{d}{dt}(fg)=f'g+fg'\\), \\(f=e^{-2(t-1)},\\ g=u(t-1)\\).</div><div class='step'><b>2) İki terim.</b> \\(f'g=-2e^{-2(t-1)}u(t-1)\\); \\(fg'=e^{-2(t-1)}\\delta(t-1)=\\delta(t-1)\\) (çünkü \\(t=1\\)'de üstel \\(=1\\)). \\[y=\\delta(t-1)-2e^{-2(t-1)}u(t-1).\\]</div>","fig":""},
{"topic":"conv","q":"\\( x(t)=u(t),\\ h(t)=2e^{-(t-4)}u(t-4) \\). Konvolüsyon?","opts":["\\( 2(1-e^{-(t-4)}) \\)","\\( 2(1+e^{-(t-4)}) \\)","\\( 4(1-e^{-(t-4)}) \\)","\\( 2(1-e^{-2(t-4)}) \\)"],"correct":0,"a":"<div class='step'><b>1) Basamak yanıtı.</b> \\(x=u\\) için \\(y(t)=\\int_{-\\infty}^{t}h(\\sigma)d\\sigma\\).</div><div class='step'><b>2) İntegre et (t>4).</b> \\[y(t)=\\int_{4}^{t}2e^{-(\\sigma-4)}d\\sigma=2\\big(1-e^{-(t-4)}\\big),\\quad t>4.\\]</div>","fig":""},
{"topic":"conv","q":"\\( x(t)=1\\ (-1\\le t\\le5),\\ h(t)=(t-1)u(t-1) \\). \\(0\\le t\\le6\\) için \\(y(t)=?\\)","opts":["\\( \\frac12 t^2 \\)","\\( -\\frac12 t^2 \\)","\\( \\frac12 t \\)","\\( \\frac14 t^2 \\)"],"correct":0,"a":"<div class='step'><b>1) İntegrali kur.</b> \\(y(t)=\\int x(\\tau)h(t-\\tau)d\\tau\\); \\(h(t-\\tau)=(t-1-\\tau)u(t-1-\\tau)\\) yani \\(\\tau\\le t-1\\). \\(x\\) ise \\(-1\\le\\tau\\le5\\).</div><div class='step'><b>2) Bu aralıkta (0≤t≤6).</b> Sınırlar \\(\\tau\\in[-1,\\,t-1]\\): \\[y=\\int_{-1}^{t-1}(t-1-\\tau)\\,d\\tau.\\]</div><div class='step'><b>3) Değişken değiştir.</b> \\(w=t-1-\\tau\\Rightarrow\\int_{0}^{t}w\\,dw=\\frac12 t^2.\\)</div>","fig":""},
{"topic":"conv","q":"Aynı \\(x,h\\). \\(t>6\\) için \\(y(t)=?\\)","opts":["\\( (6t-18)u(t-6) \\)","\\( (6t-9)u(t+6) \\)","\\( (3t+18)u(t-6) \\)","\\( (3t-18)u(t-6) \\)"],"correct":0,"a":"<div class='step'><b>1) Tam bindirme.</b> \\(t>6\\) için \\(t-1>5\\); \\(\\tau\\) tüm darbe boyunca \\([-1,5]\\): \\[y=\\int_{-1}^{5}(t-1-\\tau)\\,d\\tau.\\]</div><div class='step'><b>2) İntegre et.</b> \\[=\\Big[(t-1)\\tau-\\tfrac{\\tau^2}{2}\\Big]_{-1}^{5}=6(t-1)-12=6t-18.\\] Geçerli \\(t\\ge6\\): \\((6t-18)u(t-6)\\).</div>","fig":""},
{"topic":"conv","q":"\\( x(t)=2\\delta(t-1)-2\\delta(t-2)+5\\delta(t-4),\\ h(t)=3\\delta(t-3)+2\\delta(t-5) \\). \\(y(t)=?\\)","opts":["\\( 6\\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( \\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( 6\\delta(t-4)+6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9) \\)","\\( 6\\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)-11\\delta(t-7)+10\\delta(t-9) \\)"],"correct":0,"a":"<div class='step'><b>1) Kural.</b> \\(\\delta(t-a)*\\delta(t-b)=\\delta(t-a-b)\\); katsayılar çarpılır, gecikmeler toplanır.</div><div class='step'><b>2) Tüm çiftler.</b> \\(2\\!\\cdot\\!3@4,\\ 2\\!\\cdot\\!2@6,\\ -2\\!\\cdot\\!3@5,\\ -2\\!\\cdot\\!2@7,\\ 5\\!\\cdot\\!3@7,\\ 5\\!\\cdot\\!2@9\\). \\(@7\\): \\(-4+15=11\\).</div><div class='step'><b>3) Topla.</b> \\[y=6\\delta(t-4)-6\\delta(t-5)+4\\delta(t-6)+11\\delta(t-7)+10\\delta(t-9).\\]</div>","fig":""},
{"topic":"conv","q":"\\( x(t)=2\\sin(2\\pi t)\\,\\delta(t-\\frac14),\\ h(t)=2[u(t-2)-u(t-4)] \\). \\(y(t)=?\\)","opts":["\\( 4[u(t-2.25)-u(t-4.25)] \\)","\\( 4[u(t-2.25)+u(t-4.25)] \\)","\\( [u(t-2.25)-u(t-4.25)] \\)","\\( 2[u(t-2.25)-u(t-4.25)] \\)"],"correct":0,"a":"<div class='step'><b>1) Impulsu sadeleştir.</b> \\(f(t)\\delta(t-\\tfrac14)=f(\\tfrac14)\\delta(t-\\tfrac14)\\); \\(2\\sin(\\tfrac{\\pi}{2})=2\\Rightarrow x=2\\delta(t-\\tfrac14).\\)</div><div class='step'><b>2) Konvolüsyon = kaydırma.</b> \\(y=2\\,h(t-\\tfrac14)=2\\cdot2[u(t-2.25)-u(t-4.25)]=4[u(t-2.25)-u(t-4.25)].\\)</div>","fig":""},
{"topic":"conv","q":"\\( h[n]=(\\frac23)^n u[n],\\ x[n]=\\delta[n-2] \\). Çıkış?","opts":["\\( \\frac94(\\frac23)^n u[n-2] \\)","\\( \\frac94(\\frac23)^n u[n+2] \\)","\\( \\frac94(\\frac23)^n u[n-1] \\)","\\( \\frac49(\\frac23)^n u[n-2] \\)"],"correct":0,"a":"<div class='step'><b>1) Impulsla konvolüsyon = kaydırma.</b> \\(y[n]=h[n-2]=(\\tfrac23)^{n-2}u[n-2].\\)</div><div class='step'><b>2) Düzenle.</b> \\((\\tfrac23)^{n-2}=(\\tfrac23)^n(\\tfrac23)^{-2}=\\tfrac94(\\tfrac23)^n\\Rightarrow y[n]=\\tfrac94(\\tfrac23)^n u[n-2].\\)</div>","fig":""},
{"topic":"conv","q":"\\( y[n]=\\sum_k x[k]\\,g[n-2k],\\ g[n]=u[n]-u[n-4] \\). \\(x[n]=\\delta[n-1]\\) için \\(y[n]=?\\)","a":"<div class='step'><b>1) Tek terim kalır.</b> \\(x[k]=\\delta[k-1]\\) sadece \\(k=1\\): \\(y[n]=g[n-2]\\).</div><div class='step'><b>2) Değerler.</b> \\(g[m]=1\\) için \\(m=0,1,2,3\\Rightarrow y[n]=1\\) (\\(n=2,3,4,5\\)), diğer yerde 0.</div>","fig":""},
{"topic":"conv","q":"Aynı sistem \\( y[n]=\\sum_k x[k]g[n-2k] \\), \\(x[n]=u[n]\\) için \\(y[n]=?\\)","a":"<div class='step'><b>1) Toplam.</b> \\(y[n]=\\sum_{k\\ge0}g[n-2k]\\). Örnek değerler: \\(y[0]=g[0]=1\\), \\(y[1]=g[1]=1\\), \\(y[2]=g[2]+g[0]=2\\), \\(y[3]=g[3]+g[1]=2\\), \\(\\dots\\) \\(n\\ge2\\) için \\(2\\).</div><div class='step'><b>2) Kapalı form.</b> \\[y[n]=\\delta[n]+\\delta[n-1]+2u[n-2].\\]</div>","fig":""},

/* ---------- LAPLACE ---------- */
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2} \\), sağ taraflı (nedensel, ROC en sağda).","a":"<div class='step'><b>1) Kısmi kesir.</b> \\(\\frac{1}{s(s+1)^2}=\\frac{A}{s}+\\frac{B}{s+1}+\\frac{C}{(s+1)^2}\\). \\(A=1,\\ C=-1,\\ B=-1\\): \\[X=\\frac1s-\\frac{1}{s+1}-\\frac{1}{(s+1)^2}.\\]</div><div class='step'><b>2) Sağ taraflı ters.</b> \\(\\frac1s\\to u(t)\\), \\(\\frac{1}{s+1}\\to e^{-t}u(t)\\), \\(\\frac{1}{(s+1)^2}\\to te^{-t}u(t)\\): \\[x(t)=(1-e^{-t}-te^{-t})u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2},\\ -1<\\mathrm{Re}(s)<0 \\).","a":"<div class='step'><b>1) Aynı kısmi kesir.</b> \\(X=\\frac1s-\\frac{1}{s+1}-\\frac{1}{(s+1)^2}\\).</div><div class='step'><b>2) ROC'a göre karar.</b> ROC kutbun <i>solundaysa</i> terim sol taraflı (\\(-u(-t)\\)). Burada \\(s=0\\) kutbu ROC'un sağında \\(\\Rightarrow \\frac1s\\to -u(-t)\\); \\(s=-1\\) kutbu solunda \\(\\Rightarrow\\) sağ taraflı.</div><div class='step'><b>3) Sonuç.</b> \\[x(t)=-u(-t)-(1+t)e^{-t}u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{1}{s(s+1)^2},\\ \\mathrm{Re}(s)<-1 \\).","a":"<div class='step'><b>1) Aynı kısmi kesir.</b> Her iki kutup da ROC'un sağında \\(\\Rightarrow\\) tüm terimler sol taraflı.</div><div class='step'><b>2) Sol taraflı ters.</b> \\(\\frac1s\\to -u(-t)\\), \\(\\frac{1}{s+1}\\to -e^{-t}u(-t)\\), \\(\\frac{1}{(s+1)^2}\\to -te^{-t}u(-t)\\): \\[x(t)=(-1+e^{-t}+te^{-t})u(-t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s+1}{s^2+4s+13},\\ \\mathrm{Re}(s)>-2 \\).","a":"<div class='step'><b>1) Kareye tamamla.</b> \\(s^2+4s+13=(s+2)^2+3^2\\).</div><div class='step'><b>2) Payı ayır.</b> \\(s+1=(s+2)-1\\): \\[X=\\frac{s+2}{(s+2)^2+9}-\\frac{1}{(s+2)^2+9}.\\]</div><div class='step'><b>3) Tablodan.</b> İlki \\(e^{-2t}\\cos3t\\); ikincisi \\(\\frac13 e^{-2t}\\sin3t\\): \\[x(t)=e^{-2t}\\big(\\cos3t-\\tfrac13\\sin3t\\big)u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s}{(s^2+4)^2},\\ \\mathrm{Re}(s)>0 \\).","a":"<div class='step'><b>1) Özel çift.</b> \\(\\mathcal{L}\\{t\\sin at\\}=\\frac{2as}{(s^2+a^2)^2}\\).</div><div class='step'><b>2) Eşle.</b> \\(a=2\\): \\(\\frac{s}{(s^2+4)^2}=\\frac{1}{4}\\cdot\\frac{4s}{(s^2+4)^2}=\\frac14\\mathcal{L}\\{t\\sin2t\\}\\). \\[x(t)=\\tfrac14\\,t\\sin2t\\,u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{s}{s^3+2s^2+9s+18},\\ \\mathrm{Re}(s)>-2 \\).","a":"<div class='step'><b>1) Paydayı çarpanla.</b> \\(s^3+2s^2+9s+18=(s+2)(s^2+9)\\).</div><div class='step'><b>2) Kısmi kesir.</b> \\(\\frac{s}{(s+2)(s^2+9)}=\\frac{A}{s+2}+\\frac{Bs+C}{s^2+9}\\): \\(A=-\\frac{2}{13},\\ B=\\frac{2}{13},\\ C=\\frac{9}{13}\\).</div><div class='step'><b>3) Ters al.</b> \\[x(t)=\\Big(-\\tfrac{2}{13}e^{-2t}+\\tfrac{2}{13}\\cos3t+\\tfrac{3}{13}\\sin3t\\Big)u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"Ters Laplace: \\( X(s)=\\frac{5s+13}{s(s^2+4s+13)},\\ \\mathrm{Re}(s)>0 \\).","a":"<div class='step'><b>1) \\(c_1\\) bul.</b> \\(c_1=sX|_{s=0}=\\frac{13}{13}=1\\).</div><div class='step'><b>2) Kalanı çıkar.</b> \\(X-\\frac1s=\\frac{-s+1}{s^2+4s+13}\\). Kareye tamamla \\((s+2)^2+9\\), \\(-s+1=-(s+2)+3\\).</div><div class='step'><b>3) Ters al.</b> \\(X=\\frac1s-\\frac{s+2}{(s+2)^2+9}+\\frac{3}{(s+2)^2+9}\\): \\[x(t)=\\big[1-e^{-2t}(\\cos3t-\\sin3t)\\big]u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"İleri Laplace: \\( x(t)=(e^{-t}\\cos 2t-5e^{-2t})u(t)+\\frac12 e^{2t}u(-t) \\).","a":"<div class='step'><b>1) Terim terim.</b> \\(e^{-t}\\cos2t\\,u(t)\\to\\frac{s+1}{(s+1)^2+4}\\) (\\(\\mathrm{Re}>-1\\)); \\(-5e^{-2t}u(t)\\to\\frac{-5}{s+2}\\) (\\(\\mathrm{Re}>-2\\)).</div><div class='step'><b>2) Sol taraflı terim.</b> \\(\\frac12 e^{2t}u(-t)\\to-\\frac{1/2}{s-2}\\) (\\(\\mathrm{Re}<2\\)).</div><div class='step'><b>3) Birleştir.</b> \\[X(s)=\\frac{s+1}{(s+1)^2+4}-\\frac{5}{s+2}-\\frac{1}{2}\\frac{1}{s-2},\\quad -1<\\mathrm{Re}(s)<2.\\]</div>","fig":""},
{"topic":"laplace","q":"CT LTI: \\(x(t)=u(t)\\Rightarrow y(t)=2e^{-3t}u(t)\\). (a) \\(h(t)\\), (b) \\(x=e^{-t}u(t)\\) için \\(y(t)\\).","a":"<div class='step'><b>(a)</b> \\(X=\\frac1s,\\ Y=\\frac{2}{s+3}\\Rightarrow H=\\frac{Y}{X}=\\frac{2s}{s+3}=2-\\frac{6}{s+3}\\). \\[h(t)=2\\delta(t)-6e^{-3t}u(t).\\]</div><div class='step'><b>(b)</b> \\(X=\\frac{1}{s+1}\\): \\(Y=\\frac{2s}{(s+1)(s+3)}=-\\frac{1}{s+1}+\\frac{3}{s+3}\\). \\[y(t)=(-e^{-t}+3e^{-3t})u(t).\\]</div>","fig":""},
{"topic":"laplace","q":"\\( y''+y'-2y=x \\). (a) \\(H(s)\\); (b) \\(h(t)\\): (i) nedensel (ii) kararlı (iii) hiçbiri.","a":"<div class='step'><b>(a)</b> \\((s^2+s-2)Y=X\\Rightarrow H=\\frac{1}{(s+2)(s-1)}=\\frac13\\Big(\\frac{1}{s-1}-\\frac{1}{s+2}\\Big)\\). Kutuplar \\(s=-2,\\,1\\).</div><div class='step'><b>(i) Nedensel</b> (ROC \\(\\mathrm{Re}>1\\)): \\(h=\\frac13(e^{t}-e^{-2t})u(t)\\) (kararsız, \\(e^t\\)).</div><div class='step'><b>(ii) Kararlı</b> (ROC \\(-2<\\mathrm{Re}<1\\), \\(j\\omega\\) içerir): \\(h=-\\frac13 e^{-2t}u(t)-\\frac13 e^{t}u(-t)\\) (iki taraflı).</div><div class='step'><b>(iii) Hiçbiri</b> (ROC \\(\\mathrm{Re}<-2\\)): \\(h=\\frac13(e^{-2t}-e^{t})u(-t)\\).</div>","fig":""},
{"topic":"laplace","q":"Nedensel sistem: \\( y'(t)+2y(t)=x(t)+x'(t) \\). Dürtü yanıtı \\(h(t)=?\\)","a":"<div class='step'><b>1) Laplace.</b> \\((s+2)Y=(1+s)X\\Rightarrow H=\\frac{s+1}{s+2}\\).</div><div class='step'><b>2) Böl.</b> \\(\\frac{s+1}{s+2}=1-\\frac{1}{s+2}\\). Nedensel ters: \\[h(t)=\\delta(t)-e^{-2t}u(t).\\]</div>","fig":""},

/* ---------- Z-DÖNÜŞÜMÜ ---------- */
{"topic":"z","q":"Z-dönüşümü: (a) \\(x[n]=-a^n u[-n-1]\\), (b) \\(x[n]=a^{-n}u[-n-1]\\).","a":"<div class='step'><b>(a)</b> \\(X=-\\sum_{n=-\\infty}^{-1}a^n z^{-n}=-\\sum_{m=1}^{\\infty}(a^{-1}z)^m\\). \\(|a^{-1}z|<1\\Rightarrow|z|<|a|\\): \\[X(z)=\\frac{z}{z-a}=\\frac{1}{1-az^{-1}},\\ |z|<|a|.\\] (\\(a^n u[n]\\) ile aynı ifade, ROC farklı!)</div><div class='step'><b>(b)</b> \\(X=\\sum_{m\\ge1}(az)^m=\\frac{az}{1-az}=-\\frac{z}{z-1/a},\\ |z|<\\frac{1}{|a|}.\\)</div>","fig":""},
{"topic":"z","q":"Z-dönüşümü + kutup-sıfır: \\( x[n]=(\\frac12)^n u[n]+(\\frac13)^n u[n] \\).","a":"<div class='step'><b>1) Tablodan.</b> \\((\\tfrac12)^n u[n]\\to\\frac{z}{z-\\frac12}\\ (|z|>\\tfrac12)\\); \\((\\tfrac13)^n u[n]\\to\\frac{z}{z-\\frac13}\\ (|z|>\\tfrac13)\\).</div><div class='step'><b>2) Topla (ROC = kesişim).</b> \\[X=\\frac{z}{z-\\frac12}+\\frac{z}{z-\\frac13}=\\frac{2z\\left(z-\\frac{5}{12}\\right)}{\\left(z-\\frac12\\right)\\left(z-\\frac13\\right)},\\ |z|>\\tfrac12.\\]</div><div class='step'><b>3) Kutup-sıfır.</b> Sıfır: \\(z=0,\\ \\tfrac{5}{12}\\); kutup: \\(\\tfrac12,\\tfrac13\\); ROC \\(|z|>\\tfrac12\\) (sağ taraflı).</div>","fig":"Birim çember çiz; kutuplar × (1/2, 1/3), sıfırlar ○ (0, 5/12); ROC en dış kutbun (1/2) dışı."},
{"topic":"z","q":"Z-dönüşümü + kutup-sıfır: \\( x[n]=(\\frac13)^n u[n]+(\\frac12)^n u[-n-1] \\).","a":"<div class='step'><b>1) Tablodan.</b> \\((\\tfrac13)^n u[n]\\to\\frac{z}{z-\\frac13}\\ (|z|>\\tfrac13)\\); \\((\\tfrac12)^n u[-n-1]\\to-\\frac{z}{z-\\frac12}\\ (|z|<\\tfrac12)\\).</div><div class='step'><b>2) Topla.</b> \\[X=\\frac{z}{z-\\frac13}-\\frac{z}{z-\\frac12}=\\frac{-\\frac16\\,z}{\\left(z-\\frac12\\right)\\left(z-\\frac13\\right)},\\ \\tfrac13<|z|<\\tfrac12.\\]</div><div class='step'><b>3) Kutup-sıfır.</b> Sıfır: \\(z=0\\); kutup: \\(\\tfrac12,\\tfrac13\\); ROC = halka \\(\\tfrac13<|z|<\\tfrac12\\) (biri sağ, biri sol taraflı).</div>","fig":"ROC: 1/3 ve 1/2 kutupları arasındaki halka bölge."},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{3}{z-2},\\ |z|>2 \\).","a":"<div class='step'><b>1) Düzenle.</b> \\(X=3z^{-1}\\cdot\\frac{z}{z-2}\\).</div><div class='step'><b>2) Temel çift.</b> \\(|z|>2\\) (sağ taraflı): \\(\\frac{z}{z-2}\\leftrightarrow 2^n u[n]\\).</div><div class='step'><b>3) Kayma.</b> \\(z^{-1}\\Rightarrow n-1\\): \\[x[n]=3\\cdot2^{\\,n-1}u[n-1].\\]</div>","fig":""},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{2+z^{-2}+3z^{-4}}{z^2+4z+3},\\ |z|>0 \\) (sağ taraflı).","a":"<div class='step'><b>1) Çekirdeği çöz.</b> \\(z^2+4z+3=(z+1)(z+3)\\). \\(X_1=\\frac{z}{(z+1)(z+3)}\\Rightarrow x_1[n]=\\frac12\\big[(-1)^n-(-3)^n\\big]u[n]\\).</div><div class='step'><b>2) Doğrusallık + kayma.</b> Pay \\(2z^{-1}+z^{-3}+3z^{-5}\\) çarpanları gecikme verir: \\[x[n]=2x_1[n-1]+x_1[n-3]+3x_1[n-5].\\]</div>","fig":""},
{"topic":"z","q":"Ters Z: \\( X(z)=\\frac{1}{(1-az^{-1})^2},\\ |z|>|a| \\).","a":"<div class='step'><b>1) Özel çift.</b> \\((n+1)a^n u[n]\\leftrightarrow\\frac{1}{(1-az^{-1})^2}\\) (\\(|z|>|a|\\)).</div><div class='step'><b>2) Sonuç.</b> \\[x[n]=(n+1)a^n u[n].\\] (\\(na^n u[n]\\leftrightarrow\\frac{az^{-1}}{(1-az^{-1})^2}\\) çiftinden de türetilebilir.)</div>","fig":""},
{"topic":"z","q":"Nedensel: \\( y[n]-\\frac32 y[n-1]+\\frac12 y[n-2]=x[n]-x[n-2] \\). (b) Kararlı mı? (c) \\(x=(-1)^n u[n]\\), \\(y[-1]=y[-2]=1\\) için çıkış.","a":"<div class='step'><b>(a) Sistem fonksiyonu.</b> \\(H(z)=\\frac{1-z^{-2}}{1-\\frac32 z^{-1}+\\frac12 z^{-2}}=\\frac{(1-z^{-1})(1+z^{-1})}{(1-z^{-1})(1-\\frac12 z^{-1})}=\\frac{1+z^{-1}}{1-\\frac12 z^{-1}}\\).</div><div class='step'><b>(b) Kararlılık.</b> Tek kutup \\(z=\\tfrac12\\), birim çember içinde \\(\\Rightarrow\\) BIBO kararlı.</div><div class='step'><b>(c) Çıkış.</b> Sıfır-durum + sıfır-giriş çözümü toplanır; sonuç \\[y[n]=\\Big(1+(\\tfrac12)^n\\Big)u[n].\\]</div>","fig":""},

/* ---------- SİSTEM / SİNYAL ÖZELLİKLERİ ---------- */
{"topic":"sys","q":"\\( y(t)=x(t/2)+x(t+4) \\). Nedensellik, kararlılık, doğrusallık, zamanla değişmezlik, hafıza?","a":"<div class='step'><b>Doğrusallık:</b> Girdinin doğrusal birleşimi \\(\\Rightarrow\\) <b>doğrusal</b>.</div><div class='step'><b>Zamanla değişmezlik:</b> \\(x(t/2)\\) zaman ölçeklemesidir; girdi kaydırılınca çıkış aynı kaymaz \\(\\Rightarrow\\) <b>zamanla değişen</b>.</div><div class='step'><b>Nedensellik:</b> \\(x(t+4)\\) gelecekteki değeri kullanır \\(\\Rightarrow\\) <b>nedensel değil</b>.</div><div class='step'><b>Kararlılık:</b> Girdi sınırlıysa çıkış da sınırlı \\(\\Rightarrow\\) <b>BIBO kararlı</b>. <b>Hafızalı</b> (başka anların değerini kullanır).</div>","fig":""},
{"topic":"sys","q":"\\( y[n]=2(\\frac12)^n x[n] \\). Doğrusal ve/veya zamanla değişmez mi?","a":"<div class='step'><b>Doğrusallık:</b> \\(a x_1+b x_2\\to 2(\\tfrac12)^n(ax_1+bx_2)=a y_1+b y_2\\Rightarrow\\) <b>doğrusal</b>.</div><div class='step'><b>Zamanla değişmezlik:</b> Kaydır: \\(x[n-n_0]\\to 2(\\tfrac12)^n x[n-n_0]\\); fakat \\(y[n-n_0]=2(\\tfrac12)^{n-n_0}x[n-n_0]\\). Eşit değil (katsayı \\(n\\)'e bağlı) \\(\\Rightarrow\\) <b>zamanla değişen</b>.</div>","fig":""},
{"topic":"sys","q":"\\( h(t)=e^{-(t-1)}u(t-1) \\). Nedensel/kararlı mı? \\(x(t)=u(t+2)\\) için çıkış ne zaman başlar ve \\(y(t)=?\\)","a":"<div class='step'><b>1) Nedensel & kararlı.</b> \\(h=0,\\ t<1\\Rightarrow\\) nedensel. \\(\\int_1^\\infty e^{-(t-1)}dt=1<\\infty\\Rightarrow\\) kararlı.</div><div class='step'><b>2) Başlangıç anı.</b> \\(h\\) \\(t=1\\)'de, \\(u(t+2)\\) \\(t=-2\\)'de başlar \\(\\Rightarrow\\) çıkış \\(t_1=-1\\)'de başlar.</div><div class='step'><b>3) Çıkış.</b> \\(t>-1\\): \\(y(t)=\\int_{1}^{t+2}e^{-(\\tau-1)}d\\tau=1-e^{-(t+1)}.\\)</div>","fig":""},
{"topic":"sys","q":"\\( h(t)=e^{-2t}\\) (\\(-1<t<1\\), dışında 0). Nedensel/kararlı mı? \\(x(t)=\\delta(t+5)\\) için \\(y(t)\\)?","a":"<div class='step'><b>1) Özellikler.</b> \\(t<0\\)'da \\(h\\neq0\\Rightarrow\\) <b>nedensel değil</b>. \\(\\int_{-1}^{1}e^{-2t}dt\\) sonlu \\(\\Rightarrow\\) <b>kararlı</b>.</div><div class='step'><b>2) Impulsla yanıt.</b> \\(y(t)=h(t)*\\delta(t+5)=h(t+5)=e^{-2(t+5)}\\), geçerli \\(-1<t+5<1\\Rightarrow -6<t<-4.\\)</div>","fig":""},
{"topic":"sys","q":"Periyodiklik: (a) \\(x[n]=\\cos(n/4)\\) (b) \\(x[n]=e^{j7\\pi n/12}\\) (c) \\(x[n]=\\frac{3\\sin(\\pi n/3)}{\\pi n}\\).","a":"<div class='step'><b>(a)</b> \\(\\omega=\\tfrac14\\). \\(N\\cdot\\tfrac14=2\\pi k\\Rightarrow N=8\\pi k\\) tam sayı değil \\(\\Rightarrow\\) <b>periyodik değil</b>.</div><div class='step'><b>(b)</b> \\(\\omega=\\tfrac{7\\pi}{12}\\). \\(N=\\frac{2\\pi k}{\\omega}=\\frac{24k}{7}\\); \\(k=7\\Rightarrow N=24\\) \\(\\Rightarrow\\) <b>periyodik, \\(N=24\\)</b>.</div><div class='step'><b>(c)</b> sinc benzeri, zarf \\(\\sim 1/n\\) ile söner \\(\\Rightarrow\\) <b>periyodik değil</b>.</div>","fig":""},
{"topic":"sys","q":"Hangi ifade YANLIŞ? A) \\(\\delta[n]=u[n-1]-u[n]\\) B) \\(\\delta[n]=u[n]-u[n-1]\\) C) \\(u[n]=\\sum_{k\\ge0}\\delta[n-k]\\) D) \\(x[n]\\delta[n-n_0]=x[n_0]\\delta[n-n_0]\\)","opts":["A","B","C","D"],"correct":0,"a":"<div class='step'><b>Kontrol.</b> \\(u[n]-u[n-1]=\\delta[n]\\) doğrudur (B). Dolayısıyla \\(u[n-1]-u[n]=-\\delta[n]\\); <b>A yanlış</b>. C ve D özdeşlikleri doğrudur.</div>","fig":""},
{"topic":"sys","q":"\\(t\\ge3\\)'te yükseklik 4, \\(t<3\\)'te 0 olan sinyal?","opts":["\\( 4u(t-3) \\)","\\( 4u(t+3) \\)","\\( 4u(3-t) \\)","\\( 4\\delta(t-3) \\)"],"correct":0,"a":"<div class='step'><b>Mantık.</b> Basamak \\(u(t-3)\\) \\(t=3\\)'te 1 olur; \\(4\\) ile çarp: \\(4u(t-3)\\). \\(u(3-t)\\) tersi (\\(t<3\\)'te 1), \\(\\delta\\) ise darbe — yanlış.</div>","fig":""},
{"topic":"sys","q":"\\(1\\le t\\le4\\)'te yükseklik \\(-1\\), dışında 0 olan sinyal?","opts":["\\( u(t-4)-u(t-1) \\)","\\( u(t-1)-u(t-4) \\)","\\( -u(t+1)+u(t+4) \\)","\\( u(1-t)-u(4-t) \\)"],"correct":0,"a":"<div class='step'><b>Mantık.</b> \\([1,4]\\) darbesi \\(u(t-1)-u(t-4)\\)'tür; yükseklik \\(-1\\) için işaret ters: \\(-(u(t-1)-u(t-4))=u(t-4)-u(t-1)\\).</div>","fig":""},
{"topic":"sys","q":"\\(2\\le t\\le6\\)'da yükseklik 3 olan \\(h(t)\\)?","opts":["\\( 3u(t-2)-3u(t-6) \\)","\\( 3u(t-6)-3u(t-2) \\)","\\( 3u(t-2)+3u(t-6) \\)","\\( 3\\delta(t-2)-3\\delta(t-6) \\)"],"correct":0,"a":"<div class='step'><b>Mantık.</b> \\(t=2\\)'de yüksel (\\(+3u(t-2)\\)), \\(t=6\\)'da in (\\(-3u(t-6)\\)): \\(3u(t-2)-3u(t-6)\\) (dikdörtgen darbe).</div>","fig":""},
{"topic":"sys","q":"\\( h(t)=e^{-(t-1)}u(t-1) \\) için (A) otokorelasyon \\(R_h(\\tau)\\), (B) enerji \\(E_h\\).","a":"<div class='step'><b>(B) Enerji.</b> \\(E_h=\\int_{1}^{\\infty}e^{-2(t-1)}dt=\\tfrac12.\\)</div><div class='step'><b>(A) Otokorelasyon.</b> \\(R_h(\\tau)=\\int h(t)h(t+\\tau)dt\\). Başlangıç kayması iptal olur: \\[R_h(\\tau)=\\tfrac12 e^{-|\\tau|}.\\] \\(R_h(0)=\\tfrac12=E_h\\) (tutarlı).</div>","fig":""},

/* ---------- ÖRNEKLEME / MODÜLASYON ---------- */
{"topic":"sampling","q":"\\(T_s=0.001s\\) (1kHz), ideal LPF \\(|H|=1,\\ |\\Omega|<\\frac{\\pi}{2}\\), faz \\(-2\\Omega\\). \\(x(t)=1-\\cos(300\\pi t)+3\\sin(600\\pi t)\\) için \\(y[n]=?\\)","a":"<div class='step'><b>1) Örnekle.</b> \\(t\\to nT_s\\): \\(x[n]=1-\\cos(0{,}3\\pi n)+3\\sin(0{,}6\\pi n)\\).</div><div class='step'><b>2) Süzme.</b> Bileşenler \\(\\Omega=0,\\ 0{,}3\\pi,\\ 0{,}6\\pi\\). \\(0{,}6\\pi>\\frac{\\pi}{2}\\Rightarrow\\) süzülür (atılır).</div><div class='step'><b>3) Faz/gecikme.</b> Faz \\(-2\\Omega\\Rightarrow\\) 2 örnek gecikme. DC sabit kalır; \\(\\cos\\) terimi \\(\\cos(0{,}3\\pi(n-2))\\): \\[y[n]=1-\\cos\\big(0{,}3\\pi(n-2)\\big).\\]</div>","fig":""},
{"topic":"sampling","q":"İdeal LPF (kesim \\(\\frac{\\pi}{2}\\), gecikme 2) için dürtü yanıtı \\(h[n]=?\\)","a":"<div class='step'><b>1) Ters DTFT.</b> \\(H(e^{j\\Omega})=e^{-j2\\Omega}\\) (\\(|\\Omega|<\\frac{\\pi}{2}\\)): \\[h[n]=\\frac{1}{2\\pi}\\int_{-\\pi/2}^{\\pi/2}e^{j\\Omega(n-2)}d\\Omega.\\]</div><div class='step'><b>2) İntegre et.</b> \\[h[n]=\\frac{\\sin\\!\\big[\\frac{\\pi}{2}(n-2)\\big]}{\\pi(n-2)}.\\] (Kaydırılmış sinc.)</div>","fig":""}

];
